# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}

    # run tests!
    - run: npm run lint
    - run: npm test

jobs:
  node-v6:
    <<: *defaults
    docker:
      - image: circleci/node:6@sha256:07bc97a8ec37029c4be33ade5a4531b7dbd07fcec071d538c4556b4b89c7d952
  node-v8:
    <<: *defaults
    docker:
      - image: circleci/node:8@sha256:05e5146eb056fbc18281eef5f9c6fcf734b071a6df14e3319c60a66f3ab208fa
  node-v10:
    <<: *defaults
    docker:
      - image: circleci/node:10@sha256:f06eefa5250536041e5c9c68e06d319db56777dc8b9e91d65d56e3a8f9b53a49

workflows:
  version: 2
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10