# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}

    # run tests!
    - run: npm run lint
    - run: npm test

jobs:
  node-v6:
    <<: *defaults
    docker:
      - image: circleci/node:6@sha256:dafb94626b0dee2cda3a289bd3d10a5338ee1a14efc61b043700863375e9a626
  node-v8:
    <<: *defaults
    docker:
      - image: circleci/node:8@sha256:602bbf6938a9ebad50a7d3f5e72ca99253cf9c93805b4091aac4c5e64be1f632
  node-v10:
    <<: *defaults
    docker:
      - image: circleci/node:10@sha256:7c1c1427de666e26ca1cdfef182cfa2021b41fd69eb5b321b3cc64965f16eceb

workflows:
  version: 2
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10