blank_issues_enabled: true # Only for maintainers
contact_links:
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èªã¯ã“ã¡ã‚‰
    url: https://github.com/kintone/js-sdk-ja
    about: æ—¥æœ¬èªã§ã®ãƒã‚°å ±å‘Šãƒ»æ©Ÿèƒ½ææ¡ˆã¯ã“ã¡ã‚‰
  - name: ğŸ’¬ Questions and Help (ja)
    url: https://community.cybozu.dev/c/kintone/5
    about: Ask questions and discuss with other users in Cybozu Developer Community
  - name: ğŸŒ Questions and Help (en)
    url: https://forum.kintone.dev/
    about: Ask questions and discuss with other users in Kintone Developer Forum
  - name: ğŸ“¤ API Support
    url: https://jp.cybozu.help/k/ja/trouble_shooting/developer/developer_qa.html
    about: Contact with our API support. Suitable for API inquiries or inquiries including closed information.
